name = "HIL117"
uuid = "28c194ab-b10c-4935-839c-027c944ad6db"
authors = ["Krzysztof Miernik <k.a.miernik@gmail.com> and contributors"]
version = "1.0.0-DEV"

[deps]
TOML = "fa267f1f-6049-4f14-aa54-33bafae1ed76"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
